// Paires de mots d'Undercover : [mot A, mot B]. Au début de chaque manche, l'un va aux Civils, l'autre à l'Undercover (tirage au hasard).
// 1015 paires.
const PAIRS = [
  ["Café", "Thé"],
  ["Pizza", "Quiche"],
  ["Pomme", "Poire"],
  ["Croissant", "Pain au chocolat"],
  ["Chocolat", "Caramel"],
  ["Ketchup", "Moutarde"],
  ["Fromage", "Beurre"],
  ["Gâteau", "Tarte"],
  ["Hamburger", "Sandwich"],
  ["Miel", "Confiture"],
  ["Crêpe", "Gaufre"],
  ["Vin", "Bière"],
  ["Fraise", "Framboise"],
  ["Cerise", "Prune"],
  ["Orange", "Mandarine"],
  ["Citron", "Pamplemousse"],
  ["Banane", "Mangue"],
  ["Ananas", "Noix de coco"],
  ["Pastèque", "Melon"],
  ["Raisin", "Groseille"],
  ["Abricot", "Pêche"],
  ["Kiwi", "Fruit de la passion"],
  ["Myrtille", "Mûre"],
  ["Tomate", "Poivron"],
  ["Carotte", "Navet"],
  ["Pomme de terre", "Patate douce"],
  ["Courgette", "Concombre"],
  ["Aubergine", "Courge"],
  ["Salade", "Épinard"],
  ["Chou", "Brocoli"],
  ["Chou-fleur", "Brocoli"],
  ["Oignon", "Ail"],
  ["Échalote", "Oignon"],
  ["Poireau", "Céleri"],
  ["Champignon", "Truffe"],
  ["Haricot", "Petit pois"],
  ["Lentille", "Pois chiche"],
  ["Maïs", "Blé"],
  ["Riz", "Pâtes"],
  ["Spaghetti", "Tagliatelle"],
  ["Lasagne", "Gratin"],
  ["Couscous", "Paella"],
  ["Sushi", "Maki"],
  ["Ramen", "Pho"],
  ["Taco", "Burrito"],
  ["Kebab", "Tacos"],
  ["Hot-dog", "Hamburger"],
  ["Frites", "Chips"],
  ["Popcorn", "Chips"],
  ["Bonbon", "Sucette"],
  ["Chewing-gum", "Bonbon"],
  ["Glace", "Sorbet"],
  ["Yaourt", "Fromage blanc"],
  ["Lait", "Crème"],
  ["Beurre", "Margarine"],
  ["Huile", "Vinaigre"],
  ["Sel", "Poivre"],
  ["Sucre", "Miel"],
  ["Farine", "Levure"],
  ["Pain", "Baguette"],
  ["Brioche", "Pain de mie"],
  ["Biscotte", "Toast"],
  ["Muffin", "Cupcake"],
  ["Cookie", "Sablé"],
  ["Macaron", "Meringue"],
  ["Éclair", "Religieuse"],
  ["Mille-feuille", "Paris-Brest"],
  ["Tiramisu", "Panna cotta"],
  ["Mousse au chocolat", "Crème brûlée"],
  ["Flan", "Crème caramel"],
  ["Beignet", "Churros"],
  ["Donut", "Beignet"],
  ["Pancake", "Crêpe"],
  ["Omelette", "Œuf au plat"],
  ["Œuf", "Omelette"],
  ["Jambon", "Saucisson"],
  ["Saucisse", "Merguez"],
  ["Bacon", "Lardons"],
  ["Poulet", "Dinde"],
  ["Bœuf", "Veau"],
  ["Porc", "Agneau"],
  ["Steak", "Côtelette"],
  ["Rôti", "Gigot"],
  ["Canard", "Oie"],
  ["Lapin", "Lièvre"],
  ["Saumon", "Truite"],
  ["Thon", "Sardine"],
  ["Crevette", "Langoustine"],
  ["Homard", "Crabe"],
  ["Moule", "Huître"],
  ["Calamar", "Poulpe"],
  ["Cabillaud", "Colin"],
  ["Soupe", "Bouillon"],
  ["Velouté", "Potage"],
  ["Pot-au-feu", "Blanquette"],
  ["Raclette", "Fondue"],
  ["Tartiflette", "Raclette"],
  ["Ratatouille", "Piperade"],
  ["Cassoulet", "Choucroute"],
  ["Bouillabaisse", "Soupe de poisson"],
  ["Quiche lorraine", "Tarte flambée"],
  ["Croque-monsieur", "Croque-madame"],
  ["Pizza", "Calzone"],
  ["Ravioli", "Tortellini"],
  ["Gnocchi", "Ravioli"],
  ["Risotto", "Paella"],
  ["Curry", "Chili"],
  ["Nems", "Rouleaux de printemps"],
  ["Samoussa", "Nems"],
  ["Falafel", "Houmous"],
  ["Guacamole", "Salsa"],
  ["Mayonnaise", "Aïoli"],
  ["Pesto", "Sauce tomate"],
  ["Béchamel", "Sauce blanche"],
  ["Vinaigrette", "Mayonnaise"],
  ["Nutella", "Pâte à tartiner"],
  ["Céréales", "Muesli"],
  ["Porridge", "Muesli"],
  ["Jus d'orange", "Jus de pomme"],
  ["Limonade", "Soda"],
  ["Coca", "Pepsi"],
  ["Eau gazeuse", "Eau plate"],
  ["Smoothie", "Milkshake"],
  ["Chocolat chaud", "Café au lait"],
  ["Cappuccino", "Latte"],
  ["Expresso", "Café allongé"],
  ["Tisane", "Infusion"],
  ["Champagne", "Prosecco"],
  ["Cidre", "Poiré"],
  ["Whisky", "Rhum"],
  ["Vodka", "Gin"],
  ["Cocktail", "Mocktail"],
  ["Mojito", "Caïpirinha"],
  ["Sangria", "Punch"],
  ["Bière blonde", "Bière brune"],
  ["Vin rouge", "Vin blanc"],
  ["Rosé", "Vin blanc"],
  ["Apéritif", "Digestif"],
  ["Cacahuète", "Noisette"],
  ["Amande", "Noix"],
  ["Pistache", "Noix de cajou"],
  ["Châtaigne", "Marron"],
  ["Olive", "Cornichon"],
  ["Câpre", "Cornichon"],
  ["Avocat", "Concombre"],
  ["Radis", "Betterave"],
  ["Artichaut", "Asperge"],
  ["Endive", "Chicorée"],
  ["Persil", "Coriandre"],
  ["Basilic", "Menthe"],
  ["Thym", "Romarin"],
  ["Cannelle", "Vanille"],
  ["Gingembre", "Curcuma"],
  ["Piment", "Poivre"],
  ["Paprika", "Piment"],
  ["Moutarde", "Wasabi"],
  ["Cornet de glace", "Esquimau"],
  ["Barbe à papa", "Pomme d'amour"],
  ["Nougat", "Calisson"],
  ["Guimauve", "Chamallow"],
  ["Réglisse", "Bonbon"],
  ["Pain d'épices", "Brioche"],
  ["Galette des rois", "Bûche de Noël"],
  ["Bûche de Noël", "Gâteau d'anniversaire"],
  ["Brownie", "Fondant au chocolat"],
  ["Cheesecake", "Tarte au citron"],
  ["Clafoutis", "Far breton"],
  ["Kouign-amann", "Croissant"],
  ["Chausson aux pommes", "Croissant"],
  ["Baba au rhum", "Savarin"],
  ["Profiterole", "Chou à la crème"],
  ["Tarte aux pommes", "Tarte Tatin"],
  ["Compote", "Purée"],
  ["Purée", "Gratin dauphinois"],
  ["Frites", "Potatoes"],
  ["Petit-déjeuner", "Brunch"],
  ["Déjeuner", "Dîner"],
  ["Goûter", "Collation"],
  ["Pique-nique", "Barbecue"],
  ["Barbecue", "Plancha"],
  ["Buffet", "Self-service"],
  ["Restaurant", "Brasserie"],
  ["Fast-food", "Food truck"],
  ["Boulangerie", "Pâtisserie"],
  ["Boucherie", "Charcuterie"],
  ["Fromagerie", "Crèmerie"],
  ["Épicerie", "Supérette"],
  ["Supermarché", "Hypermarché"],
  ["Marché", "Brocante"],
  ["Chat", "Tigre"],
  ["Chien", "Loup"],
  ["Chat", "Chien"],
  ["Lion", "Tigre"],
  ["Léopard", "Guépard"],
  ["Panthère", "Jaguar"],
  ["Ours", "Panda"],
  ["Ours polaire", "Pingouin"],
  ["Pingouin", "Manchot"],
  ["Éléphant", "Mammouth"],
  ["Girafe", "Zèbre"],
  ["Zèbre", "Cheval"],
  ["Cheval", "Âne"],
  ["Poney", "Cheval"],
  ["Vache", "Taureau"],
  ["Mouton", "Chèvre"],
  ["Cochon", "Sanglier"],
  ["Lapin", "Hamster"],
  ["Hamster", "Cochon d'Inde"],
  ["Souris", "Rat"],
  ["Écureuil", "Hérisson"],
  ["Renard", "Loup"],
  ["Cerf", "Biche"],
  ["Élan", "Renne"],
  ["Chameau", "Dromadaire"],
  ["Lama", "Alpaga"],
  ["Kangourou", "Koala"],
  ["Singe", "Gorille"],
  ["Chimpanzé", "Orang-outan"],
  ["Hippopotame", "Rhinocéros"],
  ["Crocodile", "Alligator"],
  ["Serpent", "Lézard"],
  ["Tortue", "Escargot"],
  ["Grenouille", "Crapaud"],
  ["Requin", "Dauphin"],
  ["Dauphin", "Baleine"],
  ["Baleine", "Orque"],
  ["Phoque", "Otarie"],
  ["Morse", "Phoque"],
  ["Pieuvre", "Méduse"],
  ["Étoile de mer", "Oursin"],
  ["Poisson rouge", "Carpe"],
  ["Hippocampe", "Crevette"],
  ["Abeille", "Guêpe"],
  ["Fourmi", "Termite"],
  ["Papillon", "Libellule"],
  ["Mouche", "Moustique"],
  ["Coccinelle", "Scarabée"],
  ["Araignée", "Scorpion"],
  ["Sauterelle", "Criquet"],
  ["Cigale", "Grillon"],
  ["Ver de terre", "Chenille"],
  ["Escargot", "Limace"],
  ["Aigle", "Faucon"],
  ["Hibou", "Chouette"],
  ["Corbeau", "Pie"],
  ["Pigeon", "Colombe"],
  ["Moineau", "Mésange"],
  ["Perroquet", "Perruche"],
  ["Canari", "Perruche"],
  ["Cygne", "Canard"],
  ["Flamant rose", "Héron"],
  ["Cigogne", "Héron"],
  ["Poule", "Coq"],
  ["Poussin", "Caneton"],
  ["Paon", "Dindon"],
  ["Autruche", "Émeu"],
  ["Mouette", "Goéland"],
  ["Pélican", "Albatros"],
  ["Colibri", "Martin-pêcheur"],
  ["Chauve-souris", "Hibou"],
  ["Taupe", "Musaraigne"],
  ["Castor", "Loutre"],
  ["Raton laveur", "Blaireau"],
  ["Putois", "Moufette"],
  ["Hyène", "Chacal"],
  ["Gazelle", "Antilope"],
  ["Bison", "Buffle"],
  ["Yack", "Bison"],
  ["Mule", "Âne"],
  ["Licorne", "Pégase"],
  ["Dragon", "Dinosaure"],
  ["Dinosaure", "Crocodile"],
  ["T-rex", "Vélociraptor"],
  ["Phénix", "Aigle"],
  ["Sirène", "Fée"],
  ["Loup-garou", "Vampire"],
  ["Vampire", "Zombie"],
  ["Fantôme", "Esprit"],
  ["Ogre", "Géant"],
  ["Lutin", "Elfe"],
  ["Nain", "Lutin"],
  ["Sorcière", "Magicien"],
  ["Stylo", "Crayon"],
  ["Fourchette", "Cuillère"],
  ["Couteau", "Ciseaux"],
  ["Assiette", "Bol"],
  ["Verre", "Tasse"],
  ["Tasse", "Mug"],
  ["Bouteille", "Gourde"],
  ["Carafe", "Pichet"],
  ["Casserole", "Poêle"],
  ["Poêle", "Wok"],
  ["Marmite", "Cocotte"],
  ["Four", "Micro-ondes"],
  ["Frigo", "Congélateur"],
  ["Grille-pain", "Gaufrier"],
  ["Bouilloire", "Cafetière"],
  ["Mixeur", "Robot"],
  ["Fouet", "Batteur"],
  ["Spatule", "Louche"],
  ["Passoire", "Tamis"],
  ["Râpe", "Économe"],
  ["Planche à découper", "Plateau"],
  ["Nappe", "Serviette"],
  ["Torchon", "Éponge"],
  ["Lave-vaisselle", "Évier"],
  ["Lave-linge", "Sèche-linge"],
  ["Aspirateur", "Balai"],
  ["Balai", "Serpillière"],
  ["Seau", "Bassine"],
  ["Poubelle", "Corbeille"],
  ["Lampe", "Bougie"],
  ["Lampe de poche", "Lanterne"],
  ["Ampoule", "Néon"],
  ["Interrupteur", "Prise"],
  ["Rallonge", "Multiprise"],
  ["Chargeur", "Batterie"],
  ["Pile", "Batterie"],
  ["Télécommande", "Manette"],
  ["Télévision", "Ordinateur"],
  ["Ordinateur", "Tablette"],
  ["Tablette", "Liseuse"],
  ["Téléphone", "Talkie-walkie"],
  ["Smartphone", "Tablette"],
  ["Clavier", "Souris"],
  ["Écran", "Projecteur"],
  ["Imprimante", "Scanner"],
  ["Casque", "Écouteurs"],
  ["Enceinte", "Radio"],
  ["Micro", "Haut-parleur"],
  ["Appareil photo", "Caméra"],
  ["Montre", "Réveil"],
  ["Réveil", "Horloge"],
  ["Calendrier", "Agenda"],
  ["Carnet", "Cahier"],
  ["Cahier", "Classeur"],
  ["Livre", "Magazine"],
  ["Journal", "Magazine"],
  ["Bande dessinée", "Manga"],
  ["Roman", "Nouvelle"],
  ["Dictionnaire", "Encyclopédie"],
  ["Gomme", "Correcteur"],
  ["Règle", "Équerre"],
  ["Compas", "Rapporteur"],
  ["Taille-crayon", "Gomme"],
  ["Trousse", "Cartable"],
  ["Cartable", "Sac à dos"],
  ["Agrafeuse", "Trombone"],
  ["Punaise", "Aimant"],
  ["Scotch", "Colle"],
  ["Enveloppe", "Lettre"],
  ["Timbre", "Autocollant"],
  ["Carte postale", "Lettre"],
  ["Clé", "Cadenas"],
  ["Serrure", "Verrou"],
  ["Portefeuille", "Porte-monnaie"],
  ["Sac à main", "Pochette"],
  ["Valise", "Sac de voyage"],
  ["Parapluie", "Imperméable"],
  ["Lunettes", "Lentilles"],
  ["Lunettes de soleil", "Casquette"],
  ["Miroir", "Vitre"],
  ["Peigne", "Brosse"],
  ["Brosse à dents", "Fil dentaire"],
  ["Dentifrice", "Bain de bouche"],
  ["Savon", "Gel douche"],
  ["Shampoing", "Après-shampoing"],
  ["Serviette de bain", "Peignoir"],
  ["Rasoir", "Tondeuse"],
  ["Sèche-cheveux", "Lisseur"],
  ["Parfum", "Déodorant"],
  ["Maquillage", "Vernis à ongles"],
  ["Rouge à lèvres", "Gloss"],
  ["Mascara", "Eye-liner"],
  ["Crème solaire", "Après-soleil"],
  ["Pansement", "Compresse"],
  ["Thermomètre", "Stéthoscope"],
  ["Médicament", "Vitamine"],
  ["Seringue", "Vaccin"],
  ["Coussin", "Oreiller"],
  ["Couette", "Couverture"],
  ["Drap", "Housse"],
  ["Matelas", "Sommier"],
  ["Lit", "Canapé"],
  ["Canapé", "Fauteuil"],
  ["Chaise", "Tabouret"],
  ["Table", "Bureau"],
  ["Armoire", "Commode"],
  ["Étagère", "Bibliothèque"],
  ["Tiroir", "Placard"],
  ["Rideau", "Store"],
  ["Tapis", "Moquette"],
  ["Fenêtre", "Porte"],
  ["Porte", "Portail"],
  ["Escalier", "Échelle"],
  ["Ascenseur", "Escalator"],
  ["Toit", "Plafond"],
  ["Mur", "Cloison"],
  ["Cheminée", "Poêle à bois"],
  ["Radiateur", "Chauffage"],
  ["Ventilateur", "Climatiseur"],
  ["Baignoire", "Douche"],
  ["Lavabo", "Évier"],
  ["Toilettes", "Urinoir"],
  ["Robinet", "Pommeau de douche"],
  ["Vase", "Pot de fleurs"],
  ["Cadre", "Tableau"],
  ["Poster", "Affiche"],
  ["Horloge", "Pendule"],
  ["Boîte", "Coffre"],
  ["Panier", "Corbeille"],
  ["Carton", "Caisse"],
  ["Sac plastique", "Sac en papier"],
  ["Ficelle", "Corde"],
  ["Chaîne", "Corde"],
  ["Marteau", "Maillet"],
  ["Tournevis", "Clé à molette"],
  ["Perceuse", "Visseuse"],
  ["Scie", "Hache"],
  ["Pince", "Tenaille"],
  ["Clou", "Vis"],
  ["Boulon", "Écrou"],
  ["Pelle", "Pioche"],
  ["Râteau", "Binette"],
  ["Arrosoir", "Tuyau d'arrosage"],
  ["Tondeuse à gazon", "Débroussailleuse"],
  ["Brouette", "Chariot"],
  ["Cadenas", "Antivol"],
  ["Aiguille", "Épingle"],
  ["Fil", "Laine"],
  ["Bouton", "Fermeture éclair"],
  ["Dé à coudre", "Aiguille"],
  ["Ciseaux", "Cutter"],
  ["Pinceau", "Rouleau"],
  ["Peinture", "Vernis"],
  ["Feutre", "Surligneur"],
  ["Crayon de couleur", "Feutre"],
  ["Craie", "Fusain"],
  ["Tableau noir", "Tableau blanc"],
  ["Globe", "Carte"],
  ["Boussole", "GPS"],
  ["Jumelles", "Longue-vue"],
  ["Loupe", "Microscope"],
  ["Télescope", "Microscope"],
  ["Allumette", "Briquet"],
  ["Bougie", "Lampe à huile"],
  ["Éventail", "Ventilateur"],
  ["Bouillotte", "Couverture chauffante"],
  ["Balance", "Pèse-personne"],
  ["Mètre", "Règle"],
  ["Calculatrice", "Boulier"],
  ["Jeu de cartes", "Dés"],
  ["Dé", "Jeton"],
  ["Puzzle", "Rubik's cube"],
  ["Peluche", "Poupée"],
  ["Poupée", "Figurine"],
  ["Ballon", "Balle"],
  ["Cerf-volant", "Ballon de baudruche"],
  ["Toupie", "Yoyo"],
  ["Bille", "Osselet"],
  ["Trottinette", "Skateboard"],
  ["Vélo", "Trottinette"],
  ["Roller", "Patin à glace"],
  ["Luge", "Ski"],
  ["Toboggan", "Balançoire"],
  ["Balançoire", "Hamac"],
  ["Tente", "Cabane"],
  ["Sac de couchage", "Duvet"],
  ["Gourde", "Thermos"],
  ["Glacière", "Frigo"],
  ["Hamac", "Transat"],
  ["Parasol", "Parapluie"],
  ["Seau de plage", "Pelle de plage"],
  ["Bouée", "Matelas gonflable"],
  ["Masque de plongée", "Tuba"],
  ["Palmes", "Tuba"],
  ["Maillot de bain", "Bikini"],
  ["Chaussette", "Chaussure"],
  ["Chaussure", "Botte"],
  ["Basket", "Sandale"],
  ["Tong", "Sandale"],
  ["Pantoufle", "Chausson"],
  ["Escarpin", "Ballerine"],
  ["Pantalon", "Jean"],
  ["Short", "Bermuda"],
  ["Jupe", "Robe"],
  ["Robe", "Combinaison"],
  ["Chemise", "Polo"],
  ["Tee-shirt", "Débardeur"],
  ["Pull", "Gilet"],
  ["Sweat", "Pull"],
  ["Veste", "Blouson"],
  ["Manteau", "Doudoune"],
  ["Imperméable", "Coupe-vent"],
  ["Costume", "Smoking"],
  ["Cravate", "Nœud papillon"],
  ["Écharpe", "Foulard"],
  ["Bonnet", "Casquette"],
  ["Chapeau", "Béret"],
  ["Gants", "Moufles"],
  ["Ceinture", "Bretelles"],
  ["Pyjama", "Chemise de nuit"],
  ["Peignoir", "Robe de chambre"],
  ["Collant", "Legging"],
  ["Soutien-gorge", "Brassière"],
  ["Slip", "Caleçon"],
  ["Bague", "Bracelet"],
  ["Collier", "Pendentif"],
  ["Boucles d'oreilles", "Piercing"],
  ["Montre", "Bracelet"],
  ["Couronne", "Diadème"],
  ["Perruque", "Postiche"],
  ["Masque", "Déguisement"],
  ["Uniforme", "Costume"],
  ["Tablier", "Blouse"],
  ["Kimono", "Peignoir"],
  ["Toge", "Cape"],
  ["Cape", "Manteau"],
  ["Bandana", "Foulard"],
  ["Barrette", "Chouchou"],
  ["Serre-tête", "Bandeau"],
  ["Docteur", "Infirmier"],
  ["Médecin", "Dentiste"],
  ["Chirurgien", "Médecin"],
  ["Pharmacien", "Médecin"],
  ["Vétérinaire", "Médecin"],
  ["Kiné", "Ostéopathe"],
  ["Psychologue", "Psychiatre"],
  ["Policier", "Pompier"],
  ["Policier", "Gendarme"],
  ["Militaire", "Soldat"],
  ["Pilote", "Hôtesse de l'air"],
  ["Pilote", "Astronaute"],
  ["Capitaine", "Marin"],
  ["Pêcheur", "Marin"],
  ["Chauffeur de taxi", "Chauffeur de bus"],
  ["Conducteur de train", "Chauffeur de bus"],
  ["Facteur", "Livreur"],
  ["Livreur", "Coursier"],
  ["Boulanger", "Pâtissier"],
  ["Boucher", "Charcutier"],
  ["Cuisinier", "Serveur"],
  ["Serveur", "Barman"],
  ["Chef", "Commis"],
  ["Caissier", "Vendeur"],
  ["Coiffeur", "Barbier"],
  ["Esthéticienne", "Coiffeuse"],
  ["Maçon", "Plombier"],
  ["Électricien", "Plombier"],
  ["Menuisier", "Charpentier"],
  ["Peintre", "Décorateur"],
  ["Architecte", "Ingénieur"],
  ["Jardinier", "Paysagiste"],
  ["Agriculteur", "Éleveur"],
  ["Fermier", "Berger"],
  ["Professeur", "Instituteur"],
  ["Directeur", "Proviseur"],
  ["Étudiant", "Élève"],
  ["Avocat", "Juge"],
  ["Juge", "Notaire"],
  ["Banquier", "Comptable"],
  ["Journaliste", "Écrivain"],
  ["Écrivain", "Poète"],
  ["Photographe", "Caméraman"],
  ["Acteur", "Chanteur"],
  ["Chanteur", "Musicien"],
  ["Danseur", "Chorégraphe"],
  ["Réalisateur", "Producteur"],
  ["Peintre", "Sculpteur"],
  ["Clown", "Magicien"],
  ["Magicien", "Illusionniste"],
  ["Acrobate", "Jongleur"],
  ["Footballeur", "Rugbyman"],
  ["Arbitre", "Entraîneur"],
  ["Pompier", "Secouriste"],
  ["Sauveteur", "Maître-nageur"],
  ["Détective", "Espion"],
  ["Espion", "Agent secret"],
  ["Pirate", "Corsaire"],
  ["Pirate", "Viking"],
  ["Chevalier", "Samouraï"],
  ["Samouraï", "Ninja"],
  ["Roi", "Empereur"],
  ["Reine", "Princesse"],
  ["Prince", "Roi"],
  ["Président", "Ministre"],
  ["Maire", "Député"],
  ["Pape", "Évêque"],
  ["Prêtre", "Moine"],
  ["Moine", "Ermite"],
  ["Astronaute", "Cosmonaute"],
  ["Scientifique", "Chercheur"],
  ["Inventeur", "Ingénieur"],
  ["Informaticien", "Développeur"],
  ["Youtubeur", "Influenceur"],
  ["Streamer", "Youtubeur"],
  ["Mannequin", "Top model"],
  ["Guide", "Accompagnateur"],
  ["Bibliothécaire", "Libraire"],
  ["Secrétaire", "Assistant"],
  ["Agent immobilier", "Notaire"],
  ["Garagiste", "Mécanicien"],
  ["Cordonnier", "Couturier"],
  ["Couturier", "Styliste"],
  ["Bijoutier", "Horloger"],
  ["Fleuriste", "Jardinier"],
  ["Vigile", "Garde du corps"],
  ["Gardien", "Concierge"],
  ["Babysitter", "Nounou"],
  ["Nounou", "Assistante maternelle"],
  ["Chauffeur", "Pilote de course"],
  ["Dresseur", "Soigneur"],
  ["Apiculteur", "Fermier"],
  ["Bûcheron", "Forestier"],
  ["Mineur", "Ouvrier"],
  ["Explorateur", "Aventurier"],
  ["Archéologue", "Paléontologue"],
  ["Astronome", "Astrologue"],
  ["Météorologue", "Présentateur"],
  ["Présentateur", "Animateur"],
  ["DJ", "Animateur"],
  ["Cascadeur", "Doublure"],
  ["Plage", "Piscine"],
  ["Mer", "Océan"],
  ["Lac", "Étang"],
  ["Rivière", "Fleuve"],
  ["Montagne", "Colline"],
  ["Volcan", "Montagne"],
  ["Forêt", "Jungle"],
  ["Désert", "Savane"],
  ["Île", "Presqu'île"],
  ["Grotte", "Caverne"],
  ["Cascade", "Fontaine"],
  ["Falaise", "Dune"],
  ["Glacier", "Banquise"],
  ["Plaine", "Prairie"],
  ["Champ", "Pré"],
  ["Jardin", "Parc"],
  ["Potager", "Verger"],
  ["Ferme", "Grange"],
  ["Château", "Palais"],
  ["Château fort", "Forteresse"],
  ["Église", "Cathédrale"],
  ["Mosquée", "Synagogue"],
  ["Temple", "Pagode"],
  ["Maison", "Appartement"],
  ["Villa", "Manoir"],
  ["Cabane", "Chalet"],
  ["Chalet", "Refuge"],
  ["Tente", "Caravane"],
  ["Hôtel", "Auberge"],
  ["Camping", "Gîte"],
  ["Hôpital", "Clinique"],
  ["Pharmacie", "Hôpital"],
  ["École", "Collège"],
  ["Collège", "Lycée"],
  ["Université", "Grande école"],
  ["Bibliothèque", "Librairie"],
  ["Musée", "Galerie"],
  ["Cinéma", "Théâtre"],
  ["Théâtre", "Opéra"],
  ["Cirque", "Fête foraine"],
  ["Zoo", "Aquarium"],
  ["Parc d'attractions", "Fête foraine"],
  ["Stade", "Gymnase"],
  ["Piscine", "Patinoire"],
  ["Salle de sport", "Gymnase"],
  ["Discothèque", "Bar"],
  ["Bar", "Café"],
  ["Restaurant", "Cantine"],
  ["Cantine", "Réfectoire"],
  ["Gare", "Aéroport"],
  ["Aéroport", "Port"],
  ["Port", "Marina"],
  ["Métro", "Tramway"],
  ["Arrêt de bus", "Gare routière"],
  ["Station-service", "Garage"],
  ["Parking", "Garage"],
  ["Autoroute", "Nationale"],
  ["Rue", "Avenue"],
  ["Place", "Rond-point"],
  ["Pont", "Tunnel"],
  ["Phare", "Tour"],
  ["Tour Eiffel", "Arc de Triomphe"],
  ["Prison", "Commissariat"],
  ["Tribunal", "Mairie"],
  ["Mairie", "Préfecture"],
  ["Banque", "Bureau de poste"],
  ["Poste", "Banque"],
  ["Usine", "Atelier"],
  ["Bureau", "Open space"],
  ["Entrepôt", "Hangar"],
  ["Laboratoire", "Atelier"],
  ["Cimetière", "Église"],
  ["Marché", "Foire"],
  ["Centre commercial", "Galerie marchande"],
  ["Boutique", "Magasin"],
  ["Salon de coiffure", "Institut de beauté"],
  ["Spa", "Hammam"],
  ["Sauna", "Hammam"],
  ["Cuisine", "Salle à manger"],
  ["Salon", "Séjour"],
  ["Chambre", "Dortoir"],
  ["Salle de bain", "Toilettes"],
  ["Grenier", "Cave"],
  ["Cave", "Sous-sol"],
  ["Garage", "Abri de jardin"],
  ["Balcon", "Terrasse"],
  ["Véranda", "Terrasse"],
  ["Couloir", "Hall"],
  ["Jardin d'enfants", "Crèche"],
  ["Crèche", "Maternelle"],
  ["Ville", "Village"],
  ["Village", "Hameau"],
  ["Capitale", "Métropole"],
  ["Banlieue", "Campagne"],
  ["Pays", "Région"],
  ["Paris", "Londres"],
  ["Rome", "Venise"],
  ["New York", "Los Angeles"],
  ["Tokyo", "Pékin"],
  ["Espagne", "Portugal"],
  ["Italie", "Grèce"],
  ["Allemagne", "Autriche"],
  ["Belgique", "Suisse"],
  ["Canada", "États-Unis"],
  ["Brésil", "Argentine"],
  ["Mexique", "Espagne"],
  ["Égypte", "Maroc"],
  ["Japon", "Chine"],
  ["Inde", "Thaïlande"],
  ["Australie", "Nouvelle-Zélande"],
  ["Russie", "Ukraine"],
  ["Afrique", "Asie"],
  ["Europe", "Amérique"],
  ["Pôle Nord", "Pôle Sud"],
  ["Lune", "Mars"],
  ["Soleil", "Étoile"],
  ["Planète", "Étoile"],
  ["Terre", "Lune"],
  ["Galaxie", "Univers"],
  ["Comète", "Météorite"],
  ["Astéroïde", "Météorite"],
  ["Avion", "Hélicoptère"],
  ["Train", "Métro"],
  ["Voiture", "Camion"],
  ["Camion", "Camionnette"],
  ["Bus", "Car"],
  ["Taxi", "VTC"],
  ["Moto", "Scooter"],
  ["Vélo", "Moto"],
  ["Bateau", "Navire"],
  ["Voilier", "Catamaran"],
  ["Paquebot", "Ferry"],
  ["Sous-marin", "Bateau"],
  ["Canoë", "Kayak"],
  ["Barque", "Pirogue"],
  ["Jet-ski", "Bateau à moteur"],
  ["Fusée", "Navette spatiale"],
  ["Soucoupe volante", "Fusée"],
  ["Montgolfière", "Dirigeable"],
  ["Planeur", "Parapente"],
  ["Parachute", "Parapente"],
  ["Deltaplane", "Planeur"],
  ["Tracteur", "Moissonneuse"],
  ["Bulldozer", "Pelleteuse"],
  ["Grue", "Pelleteuse"],
  ["Ambulance", "Camion de pompiers"],
  ["Voiture de police", "Ambulance"],
  ["Tank", "Camion militaire"],
  ["Calèche", "Carrosse"],
  ["Traîneau", "Luge"],
  ["Téléphérique", "Télésiège"],
  ["Funiculaire", "Téléphérique"],
  ["TGV", "Train"],
  ["Tramway", "Bus"],
  ["Limousine", "Voiture de sport"],
  ["Formule 1", "Voiture de course"],
  ["Quad", "Moto"],
  ["Monocycle", "Vélo"],
  ["Tandem", "Vélo"],
  ["Trottinette électrique", "Gyroroue"],
  ["Hoverboard", "Skateboard"],
  ["Camping-car", "Caravane"],
  ["Péniche", "Bateau"],
  ["Radeau", "Bouée"],
  ["Football", "Rugby"],
  ["Basket", "Handball"],
  ["Volley", "Beach-volley"],
  ["Tennis", "Ping-pong"],
  ["Badminton", "Tennis"],
  ["Golf", "Mini-golf"],
  ["Ski", "Snowboard"],
  ["Surf", "Bodyboard"],
  ["Planche à voile", "Kitesurf"],
  ["Natation", "Plongée"],
  ["Plongée", "Snorkeling"],
  ["Course à pied", "Marathon"],
  ["Marathon", "Triathlon"],
  ["Cyclisme", "VTT"],
  ["Boxe", "Karaté"],
  ["Judo", "Karaté"],
  ["Lutte", "Sumo"],
  ["Escrime", "Kendo"],
  ["Escalade", "Alpinisme"],
  ["Randonnée", "Trekking"],
  ["Équitation", "Polo"],
  ["Gymnastique", "Danse"],
  ["Yoga", "Pilates"],
  ["Musculation", "Crossfit"],
  ["Patinage", "Hockey"],
  ["Hockey sur glace", "Hockey sur gazon"],
  ["Baseball", "Cricket"],
  ["Bowling", "Pétanque"],
  ["Pétanque", "Billard"],
  ["Billard", "Snooker"],
  ["Fléchettes", "Tir à l'arc"],
  ["Tir à l'arc", "Tir"],
  ["Pêche", "Chasse"],
  ["Échecs", "Dames"],
  ["Dames", "Backgammon"],
  ["Monopoly", "Scrabble"],
  ["Uno", "Belote"],
  ["Poker", "Blackjack"],
  ["Loto", "Bingo"],
  ["Mots croisés", "Sudoku"],
  ["Puzzle", "Mots croisés"],
  ["Cache-cache", "Chat perché"],
  ["Marelle", "Corde à sauter"],
  ["Jeu vidéo", "Jeu de société"],
  ["Console", "Ordinateur"],
  ["Karaoké", "Blind test"],
  ["Bowling", "Laser game"],
  ["Paintball", "Laser game"],
  ["Escape game", "Chasse au trésor"],
  ["Accrobranche", "Escalade"],
  ["Saut à l'élastique", "Parachute"],
  ["Rafting", "Canyoning"],
  ["Jeux olympiques", "Coupe du monde"],
  ["Champion", "Vainqueur"],
  ["Médaille", "Trophée"],
  ["Coupe", "Trophée"],
  ["But", "Panier"],
  ["Penalty", "Coup franc"],
  ["Gardien de but", "Défenseur"],
  ["Ballon de foot", "Ballon de rugby"],
  ["Raquette", "Batte"],
  ["Filet", "Panier"],
  ["Casque", "Genouillère"],
  ["Sifflet", "Carton rouge"],
  ["Podium", "Ligne d'arrivée"],
  ["Guitare", "Violon"],
  ["Piano", "Orgue"],
  ["Violon", "Violoncelle"],
  ["Batterie", "Percussions"],
  ["Trompette", "Trombone"],
  ["Saxophone", "Clarinette"],
  ["Flûte", "Clarinette"],
  ["Harpe", "Lyre"],
  ["Accordéon", "Harmonica"],
  ["Guitare électrique", "Basse"],
  ["Ukulélé", "Guitare"],
  ["Tambour", "Djembé"],
  ["Xylophone", "Triangle"],
  ["Synthétiseur", "Piano"],
  ["Micro", "Ampli"],
  ["Rock", "Métal"],
  ["Rap", "Slam"],
  ["Jazz", "Blues"],
  ["Pop", "Rock"],
  ["Reggae", "Ska"],
  ["Techno", "House"],
  ["Classique", "Opéra"],
  ["Chanson", "Comptine"],
  ["Concert", "Festival"],
  ["Orchestre", "Chorale"],
  ["Groupe", "Duo"],
  ["Album", "Single"],
  ["Clip", "Film"],
  ["Disque", "Vinyle"],
  ["CD", "Cassette"],
  ["Radio", "Podcast"],
  ["Film", "Série"],
  ["Comédie", "Drame"],
  ["Horreur", "Thriller"],
  ["Dessin animé", "Film d'animation"],
  ["Documentaire", "Reportage"],
  ["Western", "Film d'action"],
  ["Science-fiction", "Fantastique"],
  ["Roman policier", "Thriller"],
  ["Conte", "Fable"],
  ["Légende", "Mythe"],
  ["Poème", "Chanson"],
  ["Théâtre", "Comédie musicale"],
  ["Ballet", "Opéra"],
  ["Peinture", "Dessin"],
  ["Sculpture", "Statue"],
  ["Photo", "Selfie"],
  ["Tableau", "Fresque"],
  ["Graffiti", "Tag"],
  ["Mosaïque", "Vitrail"],
  ["Origami", "Pliage"],
  ["Tricot", "Crochet"],
  ["Couture", "Broderie"],
  ["Poterie", "Céramique"],
  ["Bande dessinée", "Dessin animé"],
  ["Super-héros", "Méchant"],
  ["Superman", "Batman"],
  ["Spider-Man", "Iron Man"],
  ["Harry Potter", "Le Seigneur des anneaux"],
  ["Star Wars", "Star Trek"],
  ["Mickey", "Donald"],
  ["Astérix", "Obélix"],
  ["Tintin", "Spirou"],
  ["Pikachu", "Pokémon"],
  ["Mario", "Luigi"],
  ["Sonic", "Mario"],
  ["Barbie", "Ken"],
  ["Cendrillon", "Blanche-Neige"],
  ["Blanche-Neige", "La Belle au bois dormant"],
  ["Le Petit Chaperon rouge", "Les Trois Petits Cochons"],
  ["Père Noël", "Lutin"],
  ["Lapin de Pâques", "Père Noël"],
  ["Fée", "Sorcière"],
  ["Noël", "Halloween"],
  ["Pâques", "Noël"],
  ["Mariage", "Anniversaire"],
  ["Anniversaire", "Fête"],
  ["Baptême", "Communion"],
  ["Nouvel An", "Réveillon"],
  ["Carnaval", "Mardi gras"],
  ["Saint-Valentin", "Fête des mères"],
  ["Fête des pères", "Fête des mères"],
  ["Vacances", "Week-end"],
  ["Été", "Hiver"],
  ["Printemps", "Automne"],
  ["Matin", "Soir"],
  ["Midi", "Minuit"],
  ["Jour", "Nuit"],
  ["Lundi", "Vendredi"],
  ["Janvier", "Décembre"],
  ["Rentrée", "Vacances"],
  ["Examen", "Contrôle"],
  ["Diplôme", "Certificat"],
  ["Retraite", "Vacances"],
  ["Enterrement de vie de garçon", "Mariage"],
  ["Lune de miel", "Voyage de noces"],
  ["Pique-nique", "Repas"],
  ["Soirée pyjama", "Soirée"],
  ["Feu d'artifice", "Pétard"],
  ["Cadeau", "Surprise"],
  ["Gâteau d'anniversaire", "Bougie"],
  ["Sapin de Noël", "Guirlande"],
  ["Citrouille", "Courge"],
  ["Œuf de Pâques", "Lapin en chocolat"],
  ["Confettis", "Serpentins"],
  ["Ballon", "Guirlande"],
  ["Déguisement", "Costume"],
  ["Invitation", "Faire-part"],
  ["Neige", "Glace"],
  ["Pluie", "Orage"],
  ["Orage", "Tempête"],
  ["Tempête", "Ouragan"],
  ["Tornade", "Ouragan"],
  ["Brouillard", "Nuage"],
  ["Nuage", "Fumée"],
  ["Vent", "Brise"],
  ["Arc-en-ciel", "Aurore boréale"],
  ["Éclair", "Tonnerre"],
  ["Grêle", "Neige"],
  ["Soleil", "Lune"],
  ["Chaleur", "Canicule"],
  ["Froid", "Gel"],
  ["Sécheresse", "Canicule"],
  ["Inondation", "Tsunami"],
  ["Séisme", "Tsunami"],
  ["Avalanche", "Glissement de terrain"],
  ["Feu", "Incendie"],
  ["Fleur", "Plante"],
  ["Rose", "Tulipe"],
  ["Tulipe", "Jonquille"],
  ["Marguerite", "Pâquerette"],
  ["Tournesol", "Marguerite"],
  ["Lavande", "Romarin"],
  ["Muguet", "Jacinthe"],
  ["Orchidée", "Lys"],
  ["Coquelicot", "Bleuet"],
  ["Cactus", "Aloe vera"],
  ["Arbre", "Arbuste"],
  ["Chêne", "Hêtre"],
  ["Sapin", "Pin"],
  ["Palmier", "Cocotier"],
  ["Bambou", "Roseau"],
  ["Herbe", "Gazon"],
  ["Mousse", "Lichen"],
  ["Feuille", "Pétale"],
  ["Racine", "Branche"],
  ["Graine", "Pépin"],
  ["Bois", "Écorce"],
  ["Pierre", "Rocher"],
  ["Sable", "Gravier"],
  ["Boue", "Terre"],
  ["Caillou", "Galet"],
  ["Cristal", "Diamant"],
  ["Diamant", "Rubis"],
  ["Émeraude", "Saphir"],
  ["Or", "Argent"],
  ["Argent", "Bronze"],
  ["Fer", "Acier"],
  ["Cuivre", "Bronze"],
  ["Perle", "Nacre"],
  ["Coquillage", "Escargot de mer"],
  ["Vague", "Marée"],
  ["Plage", "Crique"],
  ["Source", "Puits"]
];
