// Sujets à dessiner, rangés par catégorie. Tout le monde voit la catégorie ; seul l'imposteur ignore le sujet.
// Choisis pour être dessinables en quelques traits.
const CATEGORIES = {
  "Animaux": ["Chat", "Chien", "Éléphant", "Girafe", "Serpent", "Escargot", "Poisson", "Papillon", "Araignée", "Lapin", "Tortue", "Pingouin", "Hibou", "Requin", "Pieuvre", "Crabe", "Vache", "Cochon", "Canard", "Kangourou", "Crocodile", "Abeille", "Cheval", "Lion"],
  "Nourriture": ["Pizza", "Banane", "Pomme", "Hamburger", "Glace", "Gâteau", "Carotte", "Fraise", "Œuf au plat", "Croissant", "Sucette", "Hot-dog", "Pastèque", "Ananas", "Cerise", "Champignon", "Baguette", "Donut", "Frites", "Fromage", "Bonbon", "Brocoli", "Citron", "Spaghetti"],
  "Objets": ["Parapluie", "Lunettes", "Clé", "Ciseaux", "Ampoule", "Bougie", "Horloge", "Téléphone", "Marteau", "Chaise", "Lit", "Livre", "Crayon", "Tasse", "Bouteille", "Cadeau", "Ballon", "Valise", "Cadenas", "Loupe", "Échelle", "Brosse à dents", "Appareil photo", "Guitare"],
  "Nature": ["Soleil", "Lune", "Nuage", "Arbre", "Fleur", "Montagne", "Volcan", "Arc-en-ciel", "Étoile", "Éclair", "Vague", "Cactus", "Palmier", "Feuille", "Flocon de neige", "Goutte d'eau", "Île", "Cascade", "Tornade", "Champignon de forêt", "Rocher", "Herbe", "Sapin", "Coquillage"],
  "Transports": ["Voiture", "Vélo", "Avion", "Bateau", "Train", "Fusée", "Hélicoptère", "Moto", "Bus", "Camion", "Sous-marin", "Montgolfière", "Trottinette", "Tracteur", "Voilier", "Skateboard", "Ambulance", "Parachute", "Tramway", "Taxi", "Canoë", "Soucoupe volante", "Caravane", "Luge"],
  "Lieux": ["Maison", "Château", "Tour Eiffel", "Pyramide", "Phare", "Église", "Igloo", "Tente", "Pont", "Plage", "Désert", "Forêt", "Piscine", "École", "Hôpital", "Ferme", "Cirque", "Grotte", "Stade", "Zoo", "Moulin", "Cabane", "Gratte-ciel", "Fontaine"],
  "Corps et visage": ["Œil", "Nez", "Bouche", "Main", "Pied", "Oreille", "Dent", "Cœur", "Squelette", "Moustache", "Barbe", "Cerveau", "Langue", "Doigt", "Genou", "Sourcil", "Sourire", "Larme", "Cheveux", "Muscle", "Bras", "Empreinte", "Crâne", "Lèvres"],
  "Vêtements": ["Chapeau", "Chaussure", "Chaussette", "Tee-shirt", "Pantalon", "Robe", "Cravate", "Écharpe", "Gants", "Casquette", "Botte", "Lunettes de soleil", "Couronne", "Bonnet", "Ceinture", "Pyjama", "Maillot de bain", "Sac à dos", "Montre", "Bague", "Collier", "Tablier", "Jupe", "Short"],
  "Sports et loisirs": ["Football", "Tennis", "Basket", "Ski", "Surf", "Natation", "Boxe", "Golf", "Bowling", "Pêche", "Échecs", "Cerf-volant", "Trampoline", "Escalade", "Yoga", "Haltère", "Raquette", "Fléchettes", "Puzzle", "Dé", "Jeu vidéo", "Toboggan", "Balançoire", "Patin à glace"],
  "Métiers": ["Pompier", "Policier", "Cuisinier", "Médecin", "Pirate", "Astronaute", "Clown", "Magicien", "Peintre", "Facteur", "Jardinier", "Boulanger", "Chevalier", "Pilote", "Plongeur", "Infirmier", "Coiffeur", "Fermier", "Musicien", "Photographe", "Professeur", "Détective", "Cow-boy", "Roi"],
  "Fêtes et imaginaire": ["Sapin de Noël", "Citrouille", "Fantôme", "Sorcière", "Dragon", "Licorne", "Robot", "Extraterrestre", "Sirène", "Vampire", "Zombie", "Fée", "Père Noël", "Bonhomme de neige", "Gâteau d'anniversaire", "Feu d'artifice", "Œuf de Pâques", "Momie", "Trésor", "Baguette magique", "Chaudron", "Dinosaure", "Ange", "Monstre"],
  "Maison": ["Canapé", "Télévision", "Frigo", "Baignoire", "Toilettes", "Lampe", "Fenêtre", "Porte", "Escalier", "Cheminée", "Rideau", "Tapis", "Miroir", "Oreiller", "Four", "Aspirateur", "Machine à laver", "Robinet", "Plante verte", "Balai", "Poubelle", "Radiateur", "Armoire", "Bibliothèque"]
};
